---
dist: xenial
language: python
python:
  - 3.6
cache:
  - pip
  - apt
install:
  - pip install pipenv
  - pipenv install --dev --deploy
  - pipenv graph
script:
  - pipenv run py.test -vv --cov=gen3config --cov-report xml tests
after_script:
  - pipenv run python-codacy-coverage -r coverage.xml
before_deploy:
  - sed -i.bak "s/=get_version()/='$TRAVIS_TAG'/g" setup.py
  - cat setup.py
  - if [ $(python setup.py --version) == '0.0.0' ]; then travis_terminate 1; fi
deploy:
  provider: pypi
  user: uc-ctds
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: "XO5Ina7E8yiOJWZrSAEbdDAwMtnq/rFDBK/ksCsvHvBQZQtArnakI0GKgacMs7RIAtv2x7Iwj5ywFtG2tKvnKbsjYSFbrL+qxFH8lfSs49PkTe606hz4L92w50V7HvJzK00ML76MTVSH4VCz9Jy73xTHSFFZq2zFN89ph17ygzb+g5+Ygk0uf9VKIG5e8kejhcKDHwJtwnWg8EkNyw2HtDmKddegghvxAAmu40jOjb86EV8aKJ9Gc4Q6+MjZRXsIqEUGp7zeIt4HB9atO+356N+mkFvXcLskVYhRmqUYKgovkKsKkFG9NOcmips2zT5y6ByewXKEBbpRM7XPMdYLJvv3qK1Yc8vIEhNSah8rASgZWvYCHzfBbspv4SYeV+nBZroj/YqBxdvX3i167cH8oTCm10I37hYcYMc+idrYvBdXDDxUuii4MvGLiR11/NE7mCt1dvGef6J+/ofYdCwILTGNyEsaAXNQ2ik1O0qH4IGq+Y0Wuap0Sc2KI55/eSnrK2oXP1gSA1um2V+odz+LJcV0hw9Jd9BRhiXMX0dMmwh0WSUnMlOA8gGjG33gSEyADRz2FR9gj/NUsNSHdk9bJka9Nj5deSVBsT+kw/95MC94DGd2qpUsZ/7FHftZeGHp40bSo0dqAMiDhWjzJSj7bMU8sLyGocVWz9aOx27zcUQ="
after_deploy:
  - "./release_notes.sh"
env:
  matrix:
    - REPOSITORY="uc-cdis/gen3config" PR_NUMBER="$TRAVIS_PULL_REQUEST"
  global:
    secure: "q85vWAHrD2JzuMpggsEGV+ah1OdGxRCbxvt5OnKhJpqrVHOBX+i1vwKmk1jIvVDrrZOBFpf4rId2OHHT42Wg4JmEol/nJjsAjpC+94iqNI0dPjrocfxMGqMYAb5KXSRXtP6eY7spo5S5XE/tgSj3sOH+W0mhyU2TAi+rqu900q4eCCFjy+VR9zmZ/chpk4FEVv+T4eP8hROpoW7ZeXU6aLyRKlAKOMgKo/MqJXisMCf4bitlD1ppRGWVYiomOrQUYnVm4tZjAiwJQsam2pOv8ejXhUjUDKEeeaYxvfnGyO647jsPsD/kDcU9TlojzbFxVAQlU05Ap6eCPVYvxPhFK9OL3dlgC7/lqFBOPnNjQoiiSqah/ONGfqx/GtlP/PdSM5aVkZCTc0UOFMnx/6mIepp0m5JLdhXzznOQc00p7rxJ1RBPVXSzSuvK4VwgjWeTpU0Pu6eizLlOajsrrSqfzM7f1eDkRoOuqVAEfELfqYO7oap+Qmwf3l/o3KXX6fmBADKISzvRnvz5OD1IhWvrNLDHZ0KH6psePEvL+TON0ziEDhyujg0TM28ctBCd/wXH+aAr+Yw+g5zGvnzwHxYvtMCF2p3mR2C5Bm/h7QMPOK3ofXtO/Ae1Qz2QwMSKlc+UCmtksPRqL7QnyHdQ9fmKjAMiex2AYQSmDRuih5+rx6Q="
