---
dist: xenial
language: python
python:
  - 3.6
  - 3.7
  - 3.9
cache:
  - pip
  - apt
install:
  - pip install pipenv
  - pipenv install --dev --deploy
  - pipenv graph
script:
  - pipenv run py.test -vv --cov=gen3config --cov-report xml tests
after_script:
  - pipenv run python-codacy-coverage -r coverage.xml
before_deploy:
  - sed -i.bak "s/=get_version()/='$TRAVIS_TAG'/g" setup.py
  - cat setup.py
  - if [ $(python setup.py --version) == '0.0.0' ]; then travis_terminate 1; fi
deploy:
  provider: pypi
  user: uc-ctds
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: DJuzOrEZc830oNyPoyT92Kh6oVpDiXM/U8/neXOJPXTw1bmGw1TN8BK8zDntV7J8m7sqt6LVY48HDI1/+xL84mDwDE82+7XxBprcKRHrMidvs8orJZli3dELv46YEALdXwLcIMNQTRIgT6P6xnQhHVC2Ms60gvN1d2lnDBFY/N6uRDeeqilo7w97YNRQaugjN793wAtgADK41CxwL32sc+y7R7um31vHvnL1RgHkRxUl49rXnTttTdvwZrJKzOWKi8/Zyj7qBd9rckTICAqRmpueOSJYJy3N+R8tgN2g2dq5kOoBy1XSTjej0JJArwbBary9j8DWd8/JMtoEl7YLOub83XlEYbpjB2U1EbAbWWcWnYBmUo/IT26/T8ku1DzOqxRLXK/CS2BbDEZhe2VW4f+NILp2sKDM0zV2/ID3IXM/Kxk5yBol60D+7xh3AIi/Vav6oOMozkiFssNVLvIGN3E4/U2fbib3dHIOP46SqInW0K5o+8awRDn7ihApRG1Gqw7zDEnMA4Lo0ElcO7qYQ0NlhWhj6H8ET7V/dJdM8CkI7FTtnyRvJhqpOvIYtRfN4Vh/oSWAjQZ/3JiX6y9ygccftAd9qmSWxeAjb7lFBL53hg4/rBNLG1Ee/iy5VUyGIxBvIO/0nbpDR8lg/Ju7KfsPyhwyNeXejWAUGLAb6K4=
after_deploy:
  - "./release_notes.sh"
env:
  matrix:
    - REPOSITORY="uc-cdis/gen3config" PR_NUMBER="$TRAVIS_PULL_REQUEST"
  global:
    - secure: MArR2z1xvjiYNzyWg/pcAiYHUpyBis18Lxrc0JIj7rWWpQ10HxyuYOXyr728L3+rvVpoyB6jG+FIZHhMB3mZ4cHHx9EJZw/wO+n9GYfX+P4iYmewwxNWNI5IvPxwuJ4GBJsXvqve0FXXp0w8kQYfbquuWiY0+PoNHYlFTYQHLRRQ9c27/ls0vA9CaPgQ3NGSNJvVWktcTWfwCrcK+xutuBVuXpip/AGPqY/Gd3bFh8HKOs9rO9wxRizQF3YRA3Rz518TdTl81SHYv0oyoN8aT5f1q/XE9VowJgoDHMqep12RjngAUqjiucu/4yB98JCYvTAsP5eQ3s7IpKhSZ3vNmBUm4llmi1fyJPdvMmvrUone3rSbRrEA8oZZnUE78kJtunmO+1tpU5iY8IPzteO1zzmuJFFxIhL/MfKB4KJGaBhPgYyFhKEsspe1H5SbNE8Pa25N+SQZjMTpjC3UYiP4CmAE1QcqmfRJKAVNze6SGPm018FHautrrW3Z6K1vOgfec+q6590EtjDHtWmXccFWwTFMrbiNIr4SGg5KDIYUUarGPMQ150F6LFW6dCm9ORl2xhdmm19mDOfzChLoYNgoIRE+/25DxMN9pb0nSjS8jR2NmumaquUH8Jm9p3ZqsnNzeljLfQkwpy0sZvQ74TF0erdZqq6yVi6jONu913friaM=
