---
dist: xenial
language: python
python:
  - 3.6
cache:
  - pip
  - apt
install:
  - pip install pipenv
  - pipenv install --dev --deploy
  - pipenv graph
script:
  - pipenv run py.test -vv --cov=gen3config --cov-report xml tests
after_script:
  - pipenv run python-codacy-coverage -r coverage.xml
before_deploy:
  - sed -i.bak "s/=get_version()/='$TRAVIS_TAG'/g" setup.py
  - cat setup.py
  - if [ $(python setup.py --version) == '0.0.0' ]; then travis_terminate 1; fi
deploy:
  provider: pypi
  user: uc-ctds
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
  password:
    secure: "DJuzOrEZc830oNyPoyT92Kh6oVpDiXM/U8/neXOJPXTw1bmGw1TN8BK8zDntV7J8m7sqt6LVY48HDI1/+xL84mDwDE82+7XxBprcKRHrMidvs8orJZli3dELv46YEALdXwLcIMNQTRIgT6P6xnQhHVC2Ms60gvN1d2lnDBFY/N6uRDeeqilo7w97YNRQaugjN793wAtgADK41CxwL32sc+y7R7um31vHvnL1RgHkRxUl49rXnTttTdvwZrJKzOWKi8/Zyj7qBd9rckTICAqRmpueOSJYJy3N+R8tgN2g2dq5kOoBy1XSTjej0JJArwbBary9j8DWd8/JMtoEl7YLOub83XlEYbpjB2U1EbAbWWcWnYBmUo/IT26/T8ku1DzOqxRLXK/CS2BbDEZhe2VW4f+NILp2sKDM0zV2/ID3IXM/Kxk5yBol60D+7xh3AIi/Vav6oOMozkiFssNVLvIGN3E4/U2fbib3dHIOP46SqInW0K5o+8awRDn7ihApRG1Gqw7zDEnMA4Lo0ElcO7qYQ0NlhWhj6H8ET7V/dJdM8CkI7FTtnyRvJhqpOvIYtRfN4Vh/oSWAjQZ/3JiX6y9ygccftAd9qmSWxeAjb7lFBL53hg4/rBNLG1Ee/iy5VUyGIxBvIO/0nbpDR8lg/Ju7KfsPyhwyNeXejWAUGLAb6K4="
after_deploy:
  - "./release_notes.sh"
env:
  matrix:
    - REPOSITORY="uc-cdis/gen3config" PR_NUMBER="$TRAVIS_PULL_REQUEST"
  global:
    secure: "g/SQJl8lyBslg6fuJ/LlT2GcV5GEBwzYyVS0zXlGRaHBFM9G/QyCNj+ULhl3C7OokAsIrX8zEZm+j1y3SMKngVF6wYGZE+Ta/RmhH70ewQ3xvaJMuzdKBrOfy4uz1IYNG/Z3R6bTNMhRESdiQfATZXlyELoA6zhCYVbEfU3ajlYAryrnKvMjfEdJx1n2UXcBK3E98r7e1bkI2+6ZJawIr5CFZMpl6PH8MMoV/VcLkJzehPeekutrhosmNI1PCyGui+aWDXGBn8qSKkHq6TEiuDf8R7QcHrS94QMHpaJtCqSKw8iEA0Sfjcu45H60D69IPIbIq7YQIOl/hu00MurOHs05ezMrpMRW55yYCCFakr2qtbEw5rZvYJOhmk/8UiqmroJNSTklZYLWSs00oUJhXNPwj+O/cMvzIDJ9JGLPnUeMhjTvHHcVmBxVzHCOXlUnAEB8PMqtyaSxHaC0mH5+qronZAqJxxD6RQJkN8QpmIeWWRZmsGc3FonJa8/a23hfV6nPpYfZId+KA8CsT8waa4AczsvMMXUUFWb6aMbjvuPH0lnNu4UiouRAo6n4pDhXWYUGablw5t0sBCcR1qx15SUXv2WIOXHPu7eDtTfRHmAk+e0hUGCOLFNONXdQ7cFFTd8D5DeSK8zVqOJe0h+bjdKB8XhD/jT+GQdYyj8xofc="
